<a href="https://colab.research.google.com/github/n0rbb/IREYE4TASK_INSE/blob/main/IREYE4TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Carga de librerías e instalación de cosirrigüinchis

In [6]:
# Connect to Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
general_path = r'/content/drive/MyDrive/INSE_IREYE4TASK/'

Instalación de librerías de Octave

In [8]:
!apt-get build-dep octave
!apt install octave
!pip install oct2py
!apt-get install unzip
!apt-get install -y octave-tsa
!apt-get install -y octave-linear-algebra
!apt-get install octave-signal

Reading package lists... Done
E: You must put some 'deb-src' URIs in your sources.list
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  aglfn default-jre-headless epstool fonts-droid-fallback fonts-freefont-otf fonts-noto-mono
  fonts-urw-base35 ghostscript gnuplot-data gnuplot-qt gsfonts imagemagick-6-common info
  install-info libamd2 libauthen-sasl-perl libbtf1 libcamd2 libccolamd2 libcholmod3 libclone-perl
  libcolamd2 libcombblas1.16.0 libcxsparse3 libdata-dump-perl libemf1 libencode-locale-perl
  libevdev2 libfftw3-double3 libfftw3-long3 libfftw3-mpi3 libfftw3-single3 libfile-listing-perl
  libfltk-gl1.3 libfltk1.3 libfont-afm-perl libglpk40 libglu1-mesa libgraphicsmagick++-q16-12
  libgraphicsmagick-q16-3 libgs9 libgs9-common libgudev-1.0-0 libhdf5-openmpi-103-1
  libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl
  libhttp-cookies-p

In [9]:
from oct2py import octave

# 'octave' folder with octave files must be placed in general_path directory
octave_path = general_path + '/octave/'
octave.addpath(octave_path)

    _pyeval at line 57 column 30



'.:/usr/local/lib/python3.10/dist-packages/oct2py:/usr/local/lib/python3.10/dist-packages/octave_kernel:/usr/lib/x86_64-linux-gnu/octave/6.4.0/site/oct/x86_64-pc-linux-gnu:/usr/lib/x86_64-linux-gnu/octave/site/oct/api-v56/x86_64-pc-linux-gnu:/usr/lib/x86_64-linux-gnu/octave/site/oct/x86_64-pc-linux-gnu:/usr/share/octave/6.4.0/site/m:/usr/share/octave/site/api-v56/m:/usr/share/octave/site/m:/usr/share/octave/site/m/startup:/usr/lib/x86_64-linux-gnu/octave/6.4.0/oct/x86_64-pc-linux-gnu:/usr/share/octave/6.4.0/m:/usr/share/octave/6.4.0/m/audio:/usr/share/octave/6.4.0/m/deprecated:/usr/share/octave/6.4.0/m/elfun:/usr/share/octave/6.4.0/m/general:/usr/share/octave/6.4.0/m/geometry:/usr/share/octave/6.4.0/m/gui:/usr/share/octave/6.4.0/m/help:/usr/share/octave/6.4.0/m/image:/usr/share/octave/6.4.0/m/io:/usr/share/octave/6.4.0/m/java:/usr/share/octave/6.4.0/m/legacy:/usr/share/octave/6.4.0/m/linear-algebra:/usr/share/octave/6.4.0/m/miscellaneous:/usr/share/octave/6.4.0/m/ode:/usr/share/octave/

Instalación de librerías de Weka

In [10]:
# Install other libraries and python-weka-wrapper3
!apt-get install libproj-dev proj-data proj-bin
!apt-get install libgeos-dev
!pip install cython
!pip install python-weka-wrapper3

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libproj-dev is already the newest version (9.1.1-1~jammy0).
libproj-dev set to manually installed.
proj-data is already the newest version (9.1.1-1~jammy0).
proj-data set to manually installed.
The following NEW packages will be installed:
  proj-bin
0 upgraded, 1 newly installed, 0 to remove and 49 not upgraded.
Need to get 197 kB of archives.
After this operation, 504 kB of additional disk space will be used.
Get:1 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 proj-bin amd64 9.1.1-1~jammy0 [197 kB]
Fetched 197 kB in 1s (189 kB/s)
Selecting previously unselected package proj-bin.
(Reading database ... 134450 files and directories currently installed.)
Preparing to unpack .../proj-bin_9.1.1-1~jammy0_amd64.deb ...
Unpacking proj-bin (9.1.1-1~jammy0) ...
Setting up proj-bin (9.1.1-1~jammy0) ...
Processing triggers for man-db (2.10.2-1) ...
Reading package lists... Don

Instalación de la máquina de Java para correr Weka

In [11]:
import os #importing os to set environment variable

def install_java():
  !apt-get install -y openjdk-8-jdk-headless -qq > /dev/null # install openjdk
  os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64" # set environment variable
  !java -version # check java version

install_java()

openjdk version "11.0.25" 2024-10-15
OpenJDK Runtime Environment (build 11.0.25+9-post-Ubuntu-1ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.25+9-post-Ubuntu-1ubuntu122.04, mixed mode, sharing)


In [12]:
import weka.core.jvm as jvm

# Create new instance of java virtual machine for running weka
jvm.start(max_heap_size="8192m")

DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['/usr/local/lib/python3.10/dist-packages/weka/lib/weka.jar', '/usr/local/lib/python3.10/dist-packages/weka/lib/mtj.jar', '/usr/local/lib/python3.10/dist-packages/weka/lib/core.jar', '/usr/local/lib/python3.10/dist-packages/weka/lib/arpack_combined.jar', '/usr/local/lib/python3.10/dist-packages/weka/lib/python-weka-wrapper.jar']
DEBUG:weka.core.jvm:MaxHeapSize=8192m
DEBUG:weka.core.jvm:Package support disabled


In [13]:
# Import other libraries
from scipy.io import arff
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

##Carga de Datos

In [14]:
# Load CSV data
def DownloadDS(filename):
  df_csv = pd.read_csv(filename, sep=",", header=0, dtype = {'Var1' : 'string', 'Var2' : 'string'})
  df_csv = df_csv.drop(columns=['index', 'timestamp'], axis = 1)
  #df_csv.columns = col_names
  return df_csv


path_data = general_path + r'/dataset/data_joined13.csv'
df_csv = DownloadDS(path_data)

df_csv

Var1   Var2  eyestate        x0        x1        x2        x3  \
0       befExp  pause         0  195.0879  259.7846  335.4300  411.0754   
1       befExp  pause         0  198.0739  268.7426  340.4067  410.0801   
2       befExp  pause         0  198.0739  268.7426  340.4067  410.0801   
3       befExp  pause         0  194.0925  278.6960  341.4020  417.0474   
4       befExp  pause         0  194.0925  278.6960  341.4020  417.0474   
...        ...    ...       ...       ...       ...       ...       ...   
511255  aftExp  pause         0   69.0435  172.9759  274.0609  390.2823   
511256  aftExp  pause         0   68.4989  168.8519  270.1630  388.6808   
511257  aftExp  pause         0   68.1622  169.3502  271.2116  391.1896   
511258  aftExp  pause         0   68.0662  169.2662  274.1497  391.4979   
511259  aftExp  pause         0   66.5448  168.6875  269.6841  389.1679   

              x4        x5        x6  ...      TLL2      SLL3      TLL3  \
0       512.5995  591.2309  634.0303  ...  3.107815 -0.076645  3.101709   
1       513.5949  602.1796  631.0443  ...  3.094836 -0.069971  3.115903   
2       513.5949  602.1796  631.0443  ...  3.094836 -0.069971  3.115903   
3       511.6042  602.1796  631.0443  ...  3.130663 -0.097927  3.068872   
4       511.6042  602.1796  631.0443  ...  3.130663 -0.097927  3.068872   
...          ...       ...       ...  ...       ...       ...       ...   
511255  469.1690  520.2665  541.6042  ...  2.853212  0.122927  2.716885   
511256  471.9986  522.8846  543.1537  ...  2.830012  0.131884  2.700802   
511257  472.4816  523.5272  545.4605  ...  2.830226  0.129399  2.699457   
511258  471.8457  518.6566  541.2623  ...  2.833690  0.124378  2.708954   
511259  470.8936  520.0860  544.1558  ...  2.803251  0.118481  2.673668   

             IR0       IR1       IR2       PU0       PU1       PU2  ACTIVE  
0       0.525029  2.366637  0.493412  0.853786  0.864230 -0.010444       0  
1       0.514697  2.424762  0.453440  0.853786  0.864230 -0.010444       0  
2       0.514697  2.424762  0.453440  0.853786  0.864230 -0.010444       0  
3       0.510574  2.372166  0.482397  0.853786  0.864230 -0.010444       0  
4       0.510574  2.372166  0.482397  0.853786  0.864230 -0.010444       0  
...          ...       ...       ...       ...       ...       ...     ...  
511255  0.818098  2.527584  0.339913  0.872656  0.729576  0.143080       0  
511256  0.813626  2.533014  0.385702  0.872656  0.729576  0.143080       0  
511257  0.812846  2.573589  0.349378  0.872656  0.729576  0.143080       0  
511258  0.820429  2.582387  0.347135  0.872656  0.729576  0.143080       0  
511259  0.816602  2.571287  0.394450  0.872656  0.729576  0.143080       0  

[511260 rows x 78 columns]

#Configurador de experimentos 🔥 😙

i) Configuración de experimento (clase a evaluar)

In [29]:
percentage_test_split = 0.33
set_experiment = 1 #Variable de configuración del experimento
#0 para evaluar la clase ACTIVE
#1 para Var2
#2 para Var1

if set_experiment == 0:
  y = df_csv['ACTIVE']
elif set_experiment == 1:
  y = df_csv['Var2']
else:
  y = df_csv['Var1']


y

0         pause
1         pause
2         pause
3         pause
4         pause
          ...  
511255    pause
511256    pause
511257    pause
511258    pause
511259    pause
Name: Var2, Length: 511260, dtype: string

ii) Configuración de parámetros a utilizar

In [30]:
set_parameters = 3 #Variable de configuración de los parámetros con los que vamos a jugar
set_eyestate = 0 #Variable para mantener o no el parámetro eyestate (0 no 1 sí)
#0 - Todos
#1 - Solo las características calculadas
#2 - Solo los puntos originales
#3 - Solo mantenemos eyestate

X = df_csv.drop(columns=['ACTIVE', 'Var2', 'Var1']) #En todos los casos me cepillo las tres clases

if set_eyestate == 0 and set_parameters != 3:
  X = X.drop(columns = ['eyestate'])

dropperlist = []
if set_parameters == 1:
  dropperlist = ['x' + str(i) for i in range(28)] + ['y' + str(i) for i in range(28)]
elif set_parameters == 2:
  dropperlist = ['SUL1', 'TUL1', 'SUL2', 'TUL2', 'SUL3', 'TUL3', 'SLL1', 'TLL1', 'SLL2', 'TLL2', 'SLL3', 'TLL3', 'IR0', 'IR1', 'IR2', 'PU0', 'PU1', 'PU2']

elif set_parameters == 3:
  dropperlist = ['x' + str(i) for i in range(28)] + ['y' + str(i) for i in range(28)] + ['SUL1', 'TUL1', 'SUL2', 'TUL2', 'SUL3', 'TUL3', 'SLL1', 'TLL1', 'SLL2', 'TLL2', 'SLL3', 'TLL3', 'IR0', 'IR1', 'IR2', 'PU0', 'PU1', 'PU2']

X = X.drop(columns = dropperlist)

X


eyestate
0              0
1              0
2              0
3              0
4              0
...          ...
511255         0
511256         0
511257         0
511258         0
511259         0

[511260 rows x 1 columns]

In [31]:
X_train, X_val, y_train, y_val = train_test_split(X, y,
                                                    test_size=percentage_test_split,
                                                    random_state=42) #Luego se rehará sin splits. Todos estos datos son de train.


df_train_csv = pd.concat([X_train, y_train], axis=1).reset_index(drop=True)

df_train_csv

eyestate     Var2
0              0     Task
1              0  preTask
2              0    pause
3              0    pause
4              0  preTask
...          ...      ...
342539         0     Task
342540         0  preTask
342541         0     spkH
342542         0   rating
342543         0     spkL

[342544 rows x 2 columns]

In [32]:
df_val_csv = pd.concat([X_val, y_val], axis=1).reset_index(drop=True)

df_val_csv

eyestate     Var2
0              0    pause
1              0     Task
2              0     spkH
3              0  preTask
4              0  preTask
...          ...      ...
168711         0     Task
168712         0    lisnH
168713         0  preTask
168714         0    pause
168715         0  preTask

[168716 rows x 2 columns]

Convertir la clase a parámetro nominal

In [33]:

def get_class(experiment):
  """
  name (string) the numeric classes of the data
  """
  classes_list = []

  if experiment == 0:
    classes_list = ['IDLE', 'ACTIVE']
  elif experiment == 1:
    classes_list = ['TASK', 'LISNH', 'LISNL', 'IDLE', 'PRETASK', 'RATING', 'SPKH', 'SPKL']
  else:
    classes_list = ['AFTEXP', 'BEFEXP', 'COGH', 'COGL', 'COMH', 'COML', 'PAUSE', 'PERH', 'PERL', 'PHYH', 'PHYL']
  return classes_list


def create_class_mapping(class_names):
  """
  create dictionary classes
  """
  class_mapping = {}
  for i, class_name in enumerate(class_names):
      class_mapping[i+1] = class_name
  return class_mapping

def Convert2nominal_activities(class_number, class_mapping):
  """
  mapping classes
  """
  if class_number in class_mapping:
      return class_mapping[class_number]
  else:
      return "UNK"

In [34]:
classes_list = get_class(set_experiment)
class_mapping = create_class_mapping(classes_list)
print(' ')
print('[CLASSES]')
print(' ')
print("Defined classes are:")
for c in classes_list:
    print('\t%s' % c)

 
[CLASSES]
 
Defined classes are:
	TASK
	LISNH
	LISNL
	IDLE
	PRETASK
	RATING
	SPKH
	SPKL


In [35]:
class_mapping

{1: 'TASK',
 2: 'LISNH',
 3: 'LISNL',
 4: 'IDLE',
 5: 'PRETASK',
 6: 'RATING',
 7: 'SPKH',
 8: 'SPKL'}

Guardo como CSV


In [36]:
def Save_CSV_from_Df(df_in, output_csv_filename, experiment):
  df_out = df_in.copy()
  # Convert class data from numeric to nominal
  if experiment == 0:
    classcol = 'ACTIVE'
  elif experiment == 1:
    classcol = 'Var2'
  else:
    classcol = 'Var1'

  df_out['labels'] = df_out[classcol].replace(class_mapping)

  df_out
  # Remove numeric class and user column
  df_out = df_out.drop([classcol], axis=1)
  df_out = df_out.sort_values(by='labels')
  # Save dataframe
  df_out.to_csv(output_csv_filename, sep = ",", index=False, header=True, float_format=f'%.8f')


Save_CSV_from_Df(df_train_csv, general_path + r'/dataset/df_train_nominal.csv', set_experiment)
Save_CSV_from_Df(df_val_csv, general_path + r'/dataset/df_val_nominal.csv', set_experiment)


##Definición de las funciones de carga para Weka

In [37]:
import weka.core.jvm as jvm
from weka.core.converters import Loader, Saver
from weka.core.dataset import Instances
from weka.classifiers import Classifier, Evaluation
from weka.core.dataset import Instance
import weka.core.serialization as serialization


def LoadDatasetAsCSV(dataset_file, debug = False):
    """
    Load a dataset in a Weka known format and return it. The input dataset must have the class as the last attribute.
      :param dataset_file: Path to the input dataset in CSV format.
    """
    if debug:
       print("\n[LoadDataset]\ninput file = " + dataset_file + "\n")
    loader = Loader("weka.core.converters.CSVLoader")
    dataset = loader.load_file(dataset_file)
    dataset.class_is_last()
    return dataset


def CreateClassifier(classname="weka.classifiers.trees.J48", options=["-C", "0.25"]):
  """
    Create a new mode/classifier usig Weka.
      :param classname: This param receive the package in which the algorithm is, as it appears in Weka API. (https://weka.sourceforge.io/doc.stable/)
      :param options: List with the opcions that the algorithm accepts. This options vary with the algorithm, check Weka API for more information about
      the options that each algorithm has.
  """
  model = Classifier(classname=classname, options=options)
  return model

def LoadClassifier(classifier_file, debug=False):
    """
      Load a classifier from its saved archive ***.model .
      :param classifier_file: Path where we have the classifier saved: e.g. J48_trained_model.model
    """
    if debug:
        print("\n[LoadClassifier][" + classifier_file + "]\n")
    # read classifier object
    model = Classifier(jobject=serialization.read(classifier_file))
    print(model)
    return model

def TrainModel(train_dataset, classifier, output_path_model):
    """
      Train a built model.
      :param train_dataset: Dataset loaded in Weka format (see LoadDatasetAsCSV or LoadDataset).
      :param classifier: Classifier built or created (see CreateClassifier)
      :param output_path_model: Path where we want to save our model. e.g. "J48_trained_model.model"
    """
    #Indicate where is class label
    train_dataset.class_is_last()

    # train classifier
    classifier.build_classifier(train_dataset)

    # save classifier object
    print("\n[TrainedModel]\n\n")
    print(classifier)
    serialization.write(output_path_model, classifier)
    return classifier

def EvalClassifier(trained_classifier, train_dataset, test_dataset):
    """
      Eval a trained model.
      :param trained_classifier: Classifier built and trained(see TrainModel)
      :param train_dataset: Dataset loaded in Weka format with training data (see LoadDatasetAsCSV or LoadDataset).
      :param test_dataset: Dataset loaded in Weka format with data to test (see LoadDatasetAsCSV or LoadDataset).
    """
    evl_train = Evaluation(train_dataset)
    evl_test = Evaluation(train_dataset)
    print("--------RESULTS IN TRAINING----------")
    evl_train.test_model(trained_classifier, train_dataset)
    print(evl_train.summary())
    print("--------RESULTS IN TEST----------")
    evl_test.test_model(trained_classifier, test_dataset)
    print(evl_test.summary())
    eval_accuracy = evl_test.percent_correct
    return eval_accuracy

def Recognize(trained_classifier,test_dataset):
    """
      Make predictions of full dataset and print information of each sample results.
      :param trained_classifier: Classifier built and trained(see TrainModel)
      :param test_dataset: Dataset loaded in Weka format with data to test (see LoadDatasetAsCSV or LoadDataset).
    """
    print("# - actual - predicted - error - class distribution")
    for index, inst in enumerate(test_dataset):
      pred = trained_classifier.classify_instance(inst)
      dist = trained_classifier.distribution_for_instance(inst)
      print("%d - %s - %s - %s  - %s" %
                (index+1,
                inst.get_string_value(inst.class_index),
                inst.class_attribute.value(int(pred)),
                "yes" if pred != inst.get_value(inst.class_index) else "no",
                str(dist.tolist())))

Cargo a Weka


In [38]:
dataset_train_weka = LoadDatasetAsCSV(general_path + r'/dataset/df_train_nominal.csv', debug = False)
dataset_test_weka = LoadDatasetAsCSV(general_path + r'/dataset/df_val_nominal.csv', debug = False)

print('Sample size training: ', dataset_train_weka.num_instances)
print('Sample size testing: ', dataset_test_weka.num_instances)

Sample size training:  342544
Sample size testing:  168716


In [39]:
print(dataset_train_weka[0:24])

@relation df_train_nominal

@attribute eyestate numeric
@attribute labels {Task,lisnH,lisnL,pause,preTask,rating,spkH,spkL}

@data
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task
0,Task


##Entrenamiento de modelos de Weka

i) Weka J48

In [ ]:
print('Classifying on: ', dataset_test_weka.class_attribute)

# Create model architecture:
options_J48 = ["-C", "0.25"]
model_arquitecture = CreateClassifier(classname="weka.classifiers.trees.J48", options=options_J48)

# Train model
!cd content; mkdir models
out_path_model = "models/trained_TreeRandomForest.model" #Sin directorios, a pelo.
trained_model = TrainModel(dataset_train_weka, model_arquitecture, out_path_model)

Classifying on:  @attribute labels {Task,lisnH,lisnL,pause,preTask,rating,spkH,spkL}
/bin/bash: line 1: cd: content: No such file or directory
mkdir: cannot create directory ‘models’: File exists

[TrainedModel]


J48 pruned tree
------------------
: pause (342544.0/244390.0)

Number of Leaves  : 	1

Size of the tree : 	1



In [ ]:
raw_system_test_acc = EvalClassifier(trained_model, dataset_train_weka, dataset_test_weka)

--------RESULTS IN TRAINING----------

Correctly Classified Instances       98154               28.6544 %
Incorrectly Classified Instances    244390               71.3456 %
Kappa statistic                          0     
Mean absolute error                      0.1984
Root mean squared error                  0.3149
Relative absolute error                 99.9998 %
Root relative squared error            100      %
Total Number of Instances           342544     

--------RESULTS IN TEST----------

Correctly Classified Instances       48593               28.8017 %
Incorrectly Classified Instances    120123               71.1983 %
Kappa statistic                          0     
Mean absolute error                      0.1983
Root mean squared error                  0.3149
Relative absolute error                 99.9998 %
Root relative squared error            100      %
Total Number of Instances           168716     



no vale para mucho, pero ya que tengo la función hecha... a ver qué tal predice



In [ ]:
Recognize(trained_model, dataset_test_weka)

Streaming output truncated to the last 5000 lines.
163717 - spkL - spkL - no  - [0.0, 0.0, 0.0, 0.041666666666666664, 0.0, 0.0, 0.0, 0.9583333333333334]
163718 - spkL - spkL - no  - [0.0, 0.01282051282051282, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9871794871794872]
163719 - spkL - pause - yes  - [0.0, 0.0, 0.0, 0.6666666666666666, 0.0, 0.0, 0.0, 0.3333333333333333]
163720 - spkL - spkL - no  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
163721 - spkL - spkL - no  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
163722 - spkL - spkL - no  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
163723 - spkL - spkL - no  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
163724 - spkL - lisnH - yes  - [0.0, 0.9850746268656716, 0.0, 0.0, 0.0, 0.0, 0.0, 0.014925373134328358]
163725 - spkL - spkL - no  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
163726 - spkL - lisnH - yes  - [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
163727 - spkL - rating - yes  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.6666666666666666, 0.3333333333333333, 0.0]
163728 - spkL -

#La red recurrente LSTM

In [70]:
import tensorflow as tf
#sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print("TEST GPU is working: ", tf.test.gpu_device_name())
print("Tensorflow version:", tf.__version__)

TEST GPU is working:  
Tensorflow version: 2.17.1


In [111]:
import pandas as pd
import numpy as np

#from tensorflow.python.keras.models import Sequential
from tensorflow.keras import Sequential
#from tensorflow.python.keras.layers import LSTM, Dense
from tensorflow.keras.layers import LSTM, Dense

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

def PrepareData(df_csv, num_steps = 300, dimensions = 3):
  """
    Prepare dataset for introducing data into LSTM. One important characteristic of LSTM is that they are temporal models, so data must follow a specific shape:
    (num_samples, num_steps, num_attributes), in our case for the training set will be: (4.800, 200, 3). We use 200 timesteps (4 secs.) because each sample has this temporal resoulution, number 3 makes reference to
    the number of attributes, in our case 3 becasue we introduce information about the 3-axis of the accelerometer signal.
    This function results the dataset as X and the labels in the array y.
    :param df_csv: Dataframe with the set to convert
    :param num_steps: Number of timesteps
    :param dimensions: Number of attributes
  """

  # We select all rows (:) and all columns up to the last column (:-1).
  # This means it includes all columns except for the last one (i.e. the class).
  X_pre = df_csv.iloc[:, :-1].values

  print(df_csv.shape)
  #  y_pre will be a Pandas Series containing the data from the last column of the DataFrame df_csv.
  # The specific data in y_pre will depend on the content of that column in the DataFrame.
  y_pre = df_csv.iloc[:, -1]
  #print('y_pre')
  print(y_pre.shape)
  #print(y_pre)
  y_pre_dum = pd.get_dummies(y_pre).values
  #print('y_pre_dum')
  #print(y_pre_dum)
  X = []
  y = []

  num_samples = X_pre.shape[0]
  print('num_samples = %d (matches the number of rows)' % num_samples)
  print('num_steps = %d (matches the number of columns)' % num_steps)
  #print(X_pre)
  print(X_pre.shape)
  for j in range(num_samples):   # row
      #print('iter j=%d' % j)
      for i in range(num_steps):    # column
          #print('iter i=%d' % i)
          X.append([X_pre[j, i + (k * num_steps)] for k in range(dimensions)])

  data = np.array(X)
  X = data
  y = y_pre_dum
  print(X.shape)
  #print(y)
  X = X.reshape(-1, num_steps, dimensions)
  return X, y

def CreateLSTM(neurons_first_layer = 200, n_steps = 200, dimension = 3, loss='categorical_crossentropy',
               optimizer='rmsprop', metrics=['accuracy'], num_classes = 8):
  """
    Create LSTM model
    :param neurons_first_layer: Number of neurons of the first layer. This number can be different from the number of timesteps.
    :param n_steps: Number of timesteps of the input.
    :param dimensions: Number of attributes of the input
    :param loss: Loss function that the network will use during training for reducing its error
    :param optimez: Optimizer to use for the update rule and the training process
    :param metrics: List with the metrics to print during training
  """
  model_lstm = Sequential()
  model_lstm.add(LSTM(neurons_first_layer, input_shape=(n_steps, dimension), return_sequences=False, activation="tanh"))
  model_lstm.add(Dense(num_classes, activation='softmax'))
  model_lstm.compile(loss=loss, optimizer=optimizer, metrics=metrics)
  return model_lstm

def EvalLSTM(y_labels, y_pred, num_classes):
  """
     Eval LSTM model. Print accuracy and confussion matrix.
    :param y_labels: Original labels of the set.
    :param y_pred: Predictions of the labels for the set.
  """
  #y_test_df = pd.DataFrame({0:y_labels[:,0],
  #                          1:y_labels[:,1],
  #                          2:y_labels[:,2],
  #                          3:y_labels[:,3]})

  # Create the DataFrame using a dictionary comprehension
  y_test_df = pd.DataFrame({i: [row[i] for row in y_labels] for i in range(num_classes)})

  y_test_df_idx=y_test_df.idxmax(axis=1)

  print(confusion_matrix(y_test_df_idx, y_pred))
  print(classification_report(y_test_df_idx, y_pred))
  eval_accuracy = 100 * accuracy_score(y_test_df_idx, y_pred)
  print('Accuracy %0.4f' % eval_accuracy)

  return eval_accuracy

def CalculateCI(num_samples, accuracy):
  """
    Calculate confidence interval for a confidence of 95%
    :param num_samples: Number of samples for the set to evaluate
    :param accuracy: Accuracy of the model
  """
  return 1.96*(np.sqrt(((100-accuracy)*(accuracy))/num_samples))

def Recognize_LSTM(trained_LSTM, test_parameters, test_labels, class_mapping):
  """
    Make predictions of full dataset and print information of each sample results.
    :param trained_classifier: Classifier built and trained(see TrainModel)
    :param test_dataset: Dataset loaded in Weka format with data to test (see LoadDatasetAsCSV or LoadDataset).
  """
  y_pred = trained_LSTM.predict(test_parameters)
  print("# - actual - predicted - error - class distribution")
  for index in range(0,len(test_labels)):
    pred = Convert2nominal_activities(np.argmax(y_pred[index],axis=-1)+1, class_mapping)
    true_val = Convert2nominal_activities(np.argmax(test_labels[index],axis=-1)+1, class_mapping)
    print("%d - %s - %s - %s  - %s" %
              (index+1,
              true_val,
              pred,
              "yes" if pred != true_val else "no",
              str(y_pred[index])))



Empieza la reutilización de funciones de proceso para sacar el csv de la LSTM

In [108]:
nlstm = 'lstm_experiment' + str(set_experiment) + '.csv'
pathdata_lstm = general_path + r'/dataset/' + nlstm
df_csv_lstm = pd.read_csv(pathdata_lstm, sep=",", header=0, dtype = {'CLASS' : 'string'})

#Pido perdón por no haber usado una función y haber copiapegado celdas
oopsie = [str(elem) for elem in range(1, 18240, 76)]
print(oopsie)
print(len(oopsie))

y_lstm = df_csv_lstm['CLASS']
#print(df_csv_lstm)

X_lstm = df_csv_lstm.drop(columns = ['CLASS'])
X_lstm = X_lstm.drop(columns = oopsie)

#print(X_lstm)
#print(y_lstm)

X_train_lstm, X_val_lstm, y_train_lstm, y_val_lstm = train_test_split(X_lstm, y_lstm,
                                                    test_size=percentage_test_split,
                                                    random_state=42) #Luego se rehará sin splits. Todos estos datos son de train.


classes_list_lstm = get_class(set_experiment)
class_mapping_lstm = create_class_mapping(classes_list_lstm)
print(' ')
print('[CLASSES 4 THE LSTM]')
print(' ')
print("Defined classes are:")
for c in classes_list_lstm:
    print('\t%s' % c)





['1', '77', '153', '229', '305', '381', '457', '533', '609', '685', '761', '837', '913', '989', '1065', '1141', '1217', '1293', '1369', '1445', '1521', '1597', '1673', '1749', '1825', '1901', '1977', '2053', '2129', '2205', '2281', '2357', '2433', '2509', '2585', '2661', '2737', '2813', '2889', '2965', '3041', '3117', '3193', '3269', '3345', '3421', '3497', '3573', '3649', '3725', '3801', '3877', '3953', '4029', '4105', '4181', '4257', '4333', '4409', '4485', '4561', '4637', '4713', '4789', '4865', '4941', '5017', '5093', '5169', '5245', '5321', '5397', '5473', '5549', '5625', '5701', '5777', '5853', '5929', '6005', '6081', '6157', '6233', '6309', '6385', '6461', '6537', '6613', '6689', '6765', '6841', '6917', '6993', '7069', '7145', '7221', '7297', '7373', '7449', '7525', '7601', '7677', '7753', '7829', '7905', '7981', '8057', '8133', '8209', '8285', '8361', '8437', '8513', '8589', '8665', '8741', '8817', '8893', '8969', '9045', '9121', '9197', '9273', '9349', '9425', '9501', '9577', 

In [112]:
df_train_lstm_csv = pd.concat([X_train_lstm, y_train_lstm], axis=1).reset_index(drop=True)
df_val_lstm_csv = pd.concat([X_val_lstm, y_val_lstm], axis=1).reset_index(drop=True)


def Save_CSV_for_LSTM(df_in, output_csv_filename, experiment):
  df_out = df_in.copy()
  classcol = "CLASS"
  df_out['labels'] = df_out[classcol].replace(class_mapping)

  df_out
  # Remove numeric class and user column
  df_out = df_out.drop([classcol], axis=1)
  df_out = df_out.sort_values(by='labels')
  # Save dataframe
  df_out.to_csv(output_csv_filename, sep = ",", index=False, header=True, float_format=f'%.8f')

Save_CSV_for_LSTM(df_train_lstm_csv, general_path + r'/dataset/df_train_lstm_nominal.csv', set_experiment)
Save_CSV_for_LSTM(df_val_lstm_csv, general_path + r'/dataset/df_val_lstm_nominal.csv', set_experiment)

print(df_train_lstm_csv.shape)
print(df_val_lstm_csv.shape)
#print(df_train_lstm_csv['153'])

(171, 18001)
(85, 18001)


In [89]:
print(df_train_lstm_csv[0:10])

       0         2         3         4         5         6         7  \
0  17548   68.5109  159.4816  238.7397  345.0754  437.6185  508.8982   
1   9634   15.0681  116.0494  207.4987  302.2946  397.2753  476.1365   
2  10701  100.6278  171.8425  260.4922  371.9326  467.6013  529.1237   
3  11427   41.9759  125.6058  191.6541  265.8683  349.1154  421.4689   
4  10259    9.3235   69.4927  150.1890  265.3961  370.0162  458.9659   
5  27570   33.5922  173.2584  259.3661  380.8936  473.5389  539.5363   
6  13473   54.7783  161.2480  247.0639  361.6890  475.3371  557.7694   
7  28088  124.0338  220.0313  320.0121  440.6813  523.1028  578.9598   
8  14236  102.4036  219.1272  291.4195  392.3177  475.0284  531.4160   
9  26431  202.0689  257.5491  312.0085  398.5943  487.5649  566.4097   

          8         9        10  ...     18231     18232     18233     18234  \
0  546.6542  494.9365  418.8030  ...  3.042196  0.077174  2.965725  0.882908   
1  528.7098  471.6869  387.3071  ...  2.975434 

Preparar los datos para el LSTM

In [117]:
X_t_lstm, y_t_lstm = PrepareData(df_train_lstm_csv, num_steps = 240, dimensions = 75)
X_v_lstm, y_v_lstm = PrepareData(df_val_lstm_csv, num_steps = 240, dimensions = 75)

y_t_lstm[0:24][:]

(171, 18001)
(171,)
num_samples = 171 (matches the number of rows)
num_steps = 240 (matches the number of columns)
(171, 18000)
(41040, 75)
(85, 18001)
(85,)
num_samples = 85 (matches the number of rows)
num_steps = 240 (matches the number of columns)
(85, 18000)
(20400, 75)


array([[False, False, True, False, False, False, False, False],
       [False, False, False, False, False, True, False, False],
       [False, True, False, False, False, False, False, False],
       [True, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, False, False],
       [False, False, True, False, False, False, False, False],
       [False, False, False, False, False, True, False, False],
       [False, False, False, False, False, False, True, False],
       [False, False, False, False, False, False, False, True],
       [False, False, False, False, False, False, True, False],
       [False, True, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, False],
       [False, False, False, False, False, True, False, False],
       [True, False, False, False, False, False, False, False],
       [False, False, False, True, False, False, False, False],
       [False, False, False, False, Fals

In [121]:
print(X_t_lstm.shape)
X_t_lstm[0:10][:]

(171, 240, 75)


array([[[ 1.75480000e+04,  4.46624000e+02,  2.01658700e+02, ...,
          1.98818700e+02,  2.27425800e+02,  2.48663913e+00],
        [ 6.85109000e+01,  4.07999500e+02,  1.47639900e+02, ...,
          1.64921900e+02,  2.19088100e+02,  1.72107149e-01],
        [ 1.59481600e+02,  3.17869500e+02,  1.31362000e+02, ...,
          1.55896500e+02,  1.81667300e+02,  2.35364886e+00],
        ...,
        [ 1.61204200e+02,  2.81726700e+02,  1.72080100e+02, ...,
          1.75906700e+02,  1.45779420e-01,  8.72655946e-01],
        [ 3.43376300e+02,  3.01312000e+02,  2.40176900e+02, ...,
          2.08718600e+02,  2.75707936e+00,  7.29575934e-01],
        [ 4.33040200e+02,  2.63892800e+02,  2.89428300e+02, ...,
          2.40763700e+02,  6.90047574e-02,  1.43080012e-01]],

       [[ 9.63400000e+03,  3.99084500e+02,  2.73776400e+02, ...,
          1.92570500e+02,  3.47032800e+02,  2.19620626e+00],
        [ 1.50681000e+01,  3.43075600e+02,  2.71940600e+02, ...,
          1.38634000e+02,  3.04718700e

A entrenar el modelo

In [125]:
if set_experiment == 0:
  num_classes = 2
elif set_experiment == 1:
  num_classes = 8
else:
  num_classes = 11


callback_EarlyStopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    min_delta=0,
    patience=2,
    verbose=0,
    mode='auto',
    baseline=None,
    restore_best_weights=True
)

# LSTM model definition
model_lstm_ES = CreateLSTM(neurons_first_layer = 200,
                           n_steps = 240,
                           dimension = 75,
                           loss='categorical_crossentropy',
                           optimizer='rmsprop',
                           metrics=['accuracy'])

model_lstm_ES.add(Dense(num_classes, activation='softmax'))
print(X_t_lstm.dtype)  # Check data type of the features
print(y_t_lstm.dtype)
# Train model

y_t_lstm = y_t_lstm.astype(np.float32)
model_lstm_ES.fit(X_t_lstm,
               y_t_lstm,
               batch_size=32,
               epochs=80) # validation_data=(X_validation, y_validation),

float64
float32
Epoch 1/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 6s 407ms/step - accuracy: 0.1073 - loss: 2.0751
Epoch 2/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 416ms/step - accuracy: 0.1673 - loss: 2.0716
Epoch 3/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 5s 487ms/step - accuracy: 0.1402 - loss: 2.0666
Epoch 4/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 716ms/step - accuracy: 0.1329 - loss: 2.0648
Epoch 5/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 427ms/step - accuracy: 0.1642 - loss: 2.0595
Epoch 6/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 5s 413ms/step - accuracy: 0.1468 - loss: 2.0721
Epoch 7/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 499ms/step - accuracy: 0.1374 - loss: 2.0714
Epoch 8/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 5s 422ms/step - accuracy: 0.1305 - loss: 2.0755
Epoch 9/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 5s 416ms/step - accuracy: 0.1564 - loss: 2.0571
Epoch 10/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 424ms/step - accuracy: 0.1342 - loss: 2.0548
Epoch 11/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 718ms/step - accuracy: 0.1614 - loss: 2.0521
Epoch 12/80
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 432ms/step - accur

##Evaluación del modelo LSTM

In [128]:
# EVAL LSTM MODEL
# Predict classes on training/validation/test sets
#y_pred_train_ES = model_lstm_ES.predict_classes(X_train)
y_pred_train_x = model_lstm_ES.predict(X_v_lstm)
y_pred_train_ES = np.argmax(y_pred_train_x, axis=1)

##y_pred_val = model_lstm.predict_classes(X_validation)
#y_pred_val_x = model_lstm_ES.predict(X_validation)
#y_pred_val_ES = np.argmax(y_pred_val_x, axis=1)

#y_pred_test_ES = model_lstm_ES.predict_classes(X_test)
y_pred_test_x = model_lstm_ES.predict(X_v_lstm)
y_pred_test_ES = np.argmax(y_pred_test_x, axis=1)

# Eval model on training/validation/test sets
print("---- TRAINING RESULTS: -----")
EvalLSTM(y_v_lstm, y_pred_train_ES, num_classes)

#print("---- VALIDATION RESULTS: -----")
#EvalLSTM(y_validation, y_pred_val)

print("---- TEST RESULTS: -----")
lstm_system_test_acc = EvalLSTM(y_v_lstm, y_pred_test_ES, num_classes)

3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 265ms/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 271ms/step
---- TRAINING RESULTS: -----
[[ 0  0  0  1  0  6  3  0]
 [ 0  0  0  0  0  5  5  0]
 [ 0  0  0  0  0  7  6  0]
 [ 0  0  0  9  0  0  0  0]
 [ 0  0  0  2  0 10  2  0]
 [ 0  0  0  0  0  3  3  0]
 [ 0  0  0  0  0  7  3  0]
 [ 0  0  0  0  0  7  6  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00        10
           2       0.00      0.00      0.00        13
           3       0.75      1.00      0.86         9
           4       0.00      0.00      0.00        14
           5       0.07      0.50      0.12         6
           6       0.11      0.30      0.16        10
           7       0.00      0.00      0.00        13

    accuracy                           0.18        85
   macro avg       0.12      0.23      0.14        85
weighted avg       0.10      0.18      0.12        85

Accuracy 17.6471
---- TES

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/m

Pruebo a hacerle un PCA

In [130]:
from sklearn.decomposition import PCA


pca = PCA(n_components=75)
X_reduced = pca.fit_transform(X_t_lstm)

ValueError: Found array with dim 3. PCA expected <= 2.